apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ocpnode
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ocpnode
    app.kubernetes.io/part-of: uthocpnode
  name: ocpnode
  namespace: utherp0
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: ocpnode
status:
  loadBalancer: {}
